import Head from 'next/head'
import { useState } from 'react'

export default function Home() {
  const [theme, setTheme] = useState(true)
  return (
    <div data-theme={theme ? 'lofi' : "halloween"} className='font-poppins'>
      <Head>
        <title>LNC | THE MERN STAR.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <input onClick={() => setTheme(!theme)} type="checkbox" class="toggle" />
      <h1 className='font-tangerine text-accent'>welcome to lnc.</h1>
    </div>
  )
}
