import Head from 'next/head'

export default function Home() {
  return (
    <div className='font-poppins'>
      <Head>
        <title>LNC | LATE NIGHT CODER | THE MERN STAR.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://cdn-icons-png.flaticon.com/512/6463/6463383.png" />
      </Head>
      <div className="container mx-auto p-10 space-y-7">
        <h1 className='text-2xl'>Welcome! Lets get you updated!!</h1>
        <div className="px-5 w-2/4">
          <h2 className="text-xl">Here are the latest blogs</h2>

          <div className="container mx-auto p-3">
            <h3 className="font-semibold">learn js in 2022</h3>
            <p className="text-sm">Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas, exercitationem voluptatum fuga nisi sint est iure vel cum magnam praesentium!</p>
          </div>
          <div className="container mx-auto p-3">
            <h3 className="font-semibold">learn js in 2022</h3>
            <p className="text-sm">Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas, exercitationem voluptatum fuga nisi sint est iure vel cum magnam praesentium!</p>
          </div>
          <div className="container mx-auto p-3">
            <h3 className="font-semibold">learn js in 2022</h3>
            <p className="text-sm">Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas, exercitationem voluptatum fuga nisi sint est iure vel cum magnam praesentium!</p>
          </div>
        </div>

      </div>
    </div>
  )
}
